receivers:
  otlp:
    protocols:
      http:
        endpoint: '0.0.0.0:4318'
processors:
extensions:
  health_check: {}
exporters:
#  otlp:
#    endpoint: jaeger:4317
#    tls:
#      insecure: true
#  prometheus:
#    endpoint: "0.0.0.0:9090"
#  otlphttp:
#    endpoint: "http://0.0.0.0:3100/otlp"
  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [debug]
#      exporters: [prometheus]
    traces:
      receivers: [otlp]
      exporters: [debug]
#      exporters: [otlp]
    logs:
      receivers: [otlp]
      exporters: [debug]
#      exporters: [otlphttp]
