spring.application.name=cinema-app
server.port=8081

REGISTRATION_PASSPHRASE=secret

spring.profiles.active=live

# db
spring.datasource.url=jdbc:postgresql://localhost:5432/cinema
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.liquibase.change-log=db/changelog.xml
spring.threads.virtual.enabled=true

# api urls
cinema-city.base-url=https://www.cinema-city.pl/pl/data-api-service
helios.base-url=https://api.helios.pl/api
multikino.base-url=https://multikino.pl/api
filmweb.api.url=https://www.filmweb.pl/api
imdb.api.url=https://api.imdbapi.dev/
